name: pocketbase_utils
description: "pocketbase_utils is a dart library that generates Dart models code from a PocketBase collections scheme json file."
version: 0.1.6
repository: https://github.com/utopicnarwhal/pocketbase_utils

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer: ">=7.0.0 <9.0.0"
  args: ^2.0.0
  code_builder: ^4.9.0
  collection: ^1.18.0
  dart_style: ^3.0.1
  json_annotation: ^4.8.1
  path: ^1.8.0
  petitparser: ">=4.0.0 <8.0.0"
  yaml: ^3.0.0
  recase: ^4.1.0

dev_dependencies:
  very_good_analysis: ^9.0.0

  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^6.0.0
